<form method='post' action="<?php echo $this->getUrl("post/post/save")?>">
    <input type="hidden" class="form-control" id="id" name="id" value="<?php echo $block->getEditPost()['id'];?>">
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name" value="<?php echo $block->getEditPost()['name'];?>">
    </div>
    <div class="form-group">
        <label for="url">Url</label>
        <input type="text" class="form-control" id="url" placeholder="Enter a url" name="url" value="<?php echo $block->getEditPost()['url'];?>">
    </div>
    <div class="form-group">
        <label for="image">Image</label>
        <input type="text" class="form-control" id="image" placeholder="Enter a image" name="image" value="<?php echo $block->getEditPost()['image'];?>">
    </div>
    <div class="form-group">
        <label for="content">Content</label>
        <input type="text" class="form-control" id="content" placeholder="Enter a content" name="content" value="<?php echo $block->getEditPost()['content'];?>">
    </div>
    <div class="form-group">
        <label for="status">Status</label>
        <input type="text" class="form-control" id="status" placeholder="Enter a status" name="status" value="<?php echo $block->getEditPost()['status'];?>">
    </div>
    <div class="form-group">
        <label for="status">Status</label>
        <input class="form-check-input" type="radio" name="status" id="status1" value="1" <?php if($block->getEditPost()['status']==1) echo "checked";?>/>
        <label class="form-check-label" for="status1">
            Enable
        </label>
        <input class="form-check-input" type="radio" name="status" id="status2" value="0" <?php if($block->getEditPost()['status']==0) echo "checked";?>>
        <label class="form-check-label" for="status2">
            Disable
        </label>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
